name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm" # Thêm cache để tăng tốc độ build

      - name: 🔨 Install Dependencies
        run: npm ci # Sử dụng `npm ci` để cài đặt nhanh và chính xác

      - name: 🔨 Build Project
        run: CI=false npm run build

      - name: Update Browserslist (Optional)
        run: npx browserslist@latest --update-db # Cập nhật nếu cần

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_CPANEL_REACT_USER }}
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
